apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartlearn-courses-deployment
spec:
  selector:
    matchLabels:
      app: smartlearn-courses
  replicas: 2
  template:
    metadata:
      labels:
        app: smartlearn-courses
    spec:
      containers:
        - name: smartlearn-courses
          image: smart-learn-courses-v1
          ports:
            - containerPort: 3000
          imagePullPolicy: Never # Image should not be pulled
